### ISSUE TITLE
Problems using vsftpd as ftp-server

### ISSUE THREAD

**Issue by blinzelaffe** [cuducos/alchemydumps#12]
Hi, 
while using vsftpd as a ftp-server pushing the data to, an issue in the backup/helpers.py occurred. The response code is compared very strict against '250 OK'. With vsftpd a successfull directory-change-response get '250 Directory changed' so the socket-connection get closed in the middle of the transaction and raise an exception.

Changing.

>if change_path[0:3] != '250':
>    ftp.quit()

to

>if change_path[0:6] != '250 OK':
>    ftp.quit()

Would fix the issue. Can you please look at the issue or suggest a ftp-server, with a "250 OK" response?.

Thank you very much.
Marcus

**Comment by blinzelaffe** [comment]
Sorry the given solution should be the other way around.

Changing.

>if change_path[0:6] != '250 OK':
>      ftp.quit()

to

>if change_path[0:3] != '250':
>      ftp.quit()

Thx,
Marcus

**Comment by cuducos** [comment]
Thanks for the issue reported and possible solution, @blinzelaffe : )
I just fixed it using `change_path.startswith('250 ')` and I'm working on some minor changes to release `0.0.10` today yet, ok?

**Comment by blinzelaffe** [comment]
Thank you very much, very good flask-module indeed.

**Comment by cuducos** [comment]
Done, [version 0.0.10](https://pypi.python.org/pypi/Flask-AlchemyDumps/0.0.10) pushed to PyPI!

**Comment by blinzelaffe** [comment]
I updated to the new version and it works perfectly.
So i don't have to use a workaround anymore.
Thank you.

Marcus

**Comment by cuducos** [comment]
That's awesome : ) Thanks for the support!
(I added your name to the contributors list in the `README.md` – if you're
not _ok_ with that just drop a line.)
