### ISSUE TITLE
Use of deprecated library import

### ISSUE THREAD

**Issue by BolajiOlajide** [cuducos/alchemydumps#14]
Hello!

I tried making use of your package some days ago and I noticed this error popping on my console.
![screen shot 2017-10-10 at 21 24 38](https://user-images.githubusercontent.com/25608335/31408750-847a7b42-ae01-11e7-9c50-3239d734f945.png)

It says the import style used for `Flask_Script` is the deprecated one: `flask.ext.script`, I see in your codebase you've changed it but I doubt you've published those changes on `pypi`. Can you rectify please, thanks!

**Comment by cuducos** [comment]
I'm really sorry @BolajiOlajide. As I state in the `README.md`:

> I can't maintain this package anymore and I'd be happy to donate it to anyone willing to take it further Just drop a line ; )

So if you're willing to take over, just let me know : )

**Comment by BolajiOlajide** [comment]
Hey @cuducos ,
I'll look into it. Should send a PR soon hopefully?

**Comment by cuducos** [comment]
I'm sorry @BolajiOlajide — maybe I wasn't clear. I'm not maintaining this package anymore. I cannot promise I'll code review, merge PR… but if you wanna be the new maintainer I can grant you full permissions, or just fork it from here ; )

**Comment by BolajiOlajide** [comment]
Let me get back to you on that.

**Comment by BolajiOlajide** [comment]
Hey @cuducos 
Kindly add me as a collaborator on this project. I'll take up maintaining it as much as I can.

**Comment by cuducos** [comment]
❤️  Let's do the other way around: I'm moving the ownership to you! Are you OK with that?

If by any chance or whatever reason you are _not_ OK with that, just move the ownership back to me ; )

**Comment by cuducos** [comment]
Hum! Sorry! Just change my mind because namespace on PyPI will be an issue. So I'll add you as a collaborator so I can still push updates do PyPI and later on we find our way to manage that!
