### ISSUE TITLE
I am willing to take over this package .....

### ISSUE THREAD

**Issue by lesleslie** [cuducos/alchemydumps#16]
Hi @cuducos, I would be willing to take over management of this package.

I don't have a forked version of changes I've made to this package, but have modified a majority of the code and placed inside another app of mine (running python 3.6 on an AWS Lambda). If I was given maintership of this package this is the direction I would like to take it in based on my current modifications:

- Make the package python3 only
- Add saving to a S3 bucket in addition to ftp
- Add utilities for working within the AWS cloud (and eventually others)
- Add support for many to many relationships (in progress - i have one issue, not backing up but restoring, with this left and will have it knocked out soon)
- Continued flask integration (possibly rename to flask-alchemydumps?)
- Corresponding documentation

Thanks for the code! This package was really, really, helpful in building my latest application and I'd love the chance to take it in new directions for others to enjoy.

-- les

**Comment by lesleslie** [comment]
and if there are no objections, I would like to switch the testing from tox to pytest

**Comment by cuducos** [comment]
Yay, sounds perfect : )
I like the list of improvements and I might contribute one or other day…

Let me know how do you prefer to take over. We can still use this repo (as some links might point users here) and I add you as a contributor/maintainer/admin, or you can start your own repo/fork and I archive this one pointing users to yours, or I can try to transfer you this repo. (Same for PyPI, except we should avoid namespace conflict — so either I add you or I transfer the package). TBH for me either way works just fine.

I'd also would like to know if you want me around or if you wanna me out of your way ; ) And, again, either way works just fine. Just let me know so I actually help and don't become a burden hahaha…

**Comment by lesleslie** [comment]
Tell you what, you can go ahead and add me as maintainer if you want. I
will go ahead and do some modifications to a fork and make a pull request
or two. If you like the changes, we can chat further and take it from there.

And yes, I'd love to have you around.

Les Leslie
Principal / Developer
Wedgwood Web Works
les@wedgwoodwebworks.com
(406) 640-4222

**Comment by cuducos** [comment]
Done : )
Welcome aboard 👨‍✈️

**Comment by lesleslie** [comment]
Just a quick note.

I'm still avidly interested in taking over this project. It might be a little while until I can make updates and backport some changes I've made to the codebase though. Just really busy right now. I'll get to it as soon as I can.

Thank you,

-- les

**Comment by cuducos** [comment]
Closed by inactivity.
