### ISSUE TITLE
Licensing Request

### ISSUE THREAD

**Issue by gnubyte** [cuducos/alchemydumps#17]
Hi, Can we please assign a license, MIT license or otherwise, to this repository?

Thank you!

**Comment by cuducos** [comment]
It's already there (bottom of the `READE.md`) for 5 years: https://github.com/cuducos/alchemydumps/commit/e7783134a40f6d65bb717cd25321f85b27b1a117#diff-c47c7c7383225ab55ff591cb59c41e6bR112

 Feel free to open a PR and create the `LICENSE` file is that is what you mean ; )
