### ISSUE TITLE
How to write this package as a Flask extension and not merely a Python package?

### ISSUE THREAD

**Issue by cuducos** [cuducos/alchemydumps#3]

**Comment by spikergit1** [comment]
Hey, you might want to check out http://flask.pocoo.org/docs/0.10/extensiondev/

> Extensions are all located in a package called flask_something where “something” is the name of the library you want to bridge. So for example if you plan to add support for a library named simplexml to Flask, you would name your extension’s package flask_simplexml.

> The name of the actual extension (the human readable name) however would be something like “Flask-SimpleXML”. Make sure to include the name “Flask” somewhere in that name and that you check the capitalization. This is how users can then register dependencies to your extension in their setup.py files.

> Flask sets up a redirect package called flask.ext where users should import the extensions from. If you for instance have a package called flask_something users would import it as flask.ext.something. This is done to transition from the old namespace packages. See Extension Import Transition for more details.

So basically you'd need to rename the project, afaik.

**Comment by cuducos** [comment]
Many many thanks, @spikergit1 !
Just did and worked perfectly :)
