### ISSUE TITLE
Multiple models with abstract (not working)

### ISSUE THREAD

**Issue by antwal** [cuducos/alchemydumps#6]
Hi,

I have a multiple models with abstract model; it not working

Thanks.

**Comment by cuducos** [comment]
Hey @antwal, thanks for the report.

Can you share the model you are using, so I can try to reproduce the environment and (hopefully) fix the bug?

Cheers

**Comment by antwal** [comment]
Hi,

this is example;

# abstract.py
class Base(db.Model):
    __abstract__  = True

    id = db.Column(db.Integer, primary_key=True)

# users.py
class Users(Base):
    __tablename__ = 'users'

    client = db.Column(db.String(12))
    address = db.Column(db.String(15))

    def __init__(self, client=None, address=None):
        self.client = client
        self.address = address


I have used your example to create backups; but not working; I have tryed with standard example working.

Thanks.

**Comment by cuducos** [comment]
Thanks. I'll try to take a look during the weekend.
(But surely anyone is free to send a PR)

**Comment by cuducos** [comment]
Hey @antwal,

I couldn't fix it, but probably the problem comes form the fact that:

> `__abstract__` causes declarative to skip the production of a table or mapper for the class entirely [[source](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/declarative/api.html?highlight=abstract#abstract)]

AlchemyDumps backs up mapped class only. I'm not sure how to get non-mapped class.
