### ISSUE TITLE
Allow usage with app factory pattern

### ISSUE THREAD

**Issue by italomaia** [cuducos/alchemydumps#7]
In case my flask script manager is created using a factory pattern, like this:

    manager = script.Manager(app_factory)

How am I supposed to initialize Dumps?

**Comment by cuducos** [comment]
Hi @italomaia

Unfortunately I'm a beginner and I'm not sure I'm approaching your doubt properly. Anyway, if the type returned by `script.Manager()` is compatible with the standard `Manager()` from [Flask-Script](https://github.com/smurfix/flask-script), the normal instructions should work. What I mean is (assuming you have installed AlchemyDumps, `pip install Flask-AlchemyDumps`):

```
…
from flask.ext.alchemydumps import AlchemyDumps, AlchemyDumpsCommand
…
manager = script.Manager(app_factory)
…
alchemydumps = AlchemyDumps(app, db)
manager.add_command('alchemydumps', AlchemyDumpsCommand)
```

Have you tried that and got any error?

Many thanks

**Comment by vlikin** [comment]
http://flask.pocoo.org/docs/0.10/patterns/appfactories/#application-factories
Yes,  the factory approach is very flexible. You should mention it in the documentation.

I do this way. I looked over the code. It should support.

# Dumps.
from flask.ext.alchemydumps import AlchemyDumps, AlchemyDumpsCommand
dumps = AlchemyDumps()

# Script manager.
from flask.ext.script import Manager as ScriptManager
script_manager = ScriptManager()
script_manager.add_command('dumps', AlchemyDumpsCommand)


def create_app(config_filename):
    """
      - It creates the Flask application <- Factory.

      :param config_filename:
      :return: Flask
    """
    app = Flask(__name__)
    ...
    dumps.init_app(app, db, basedir='tests/')
    ...

    return app

**Comment by cuducos** [comment]
Fell free to add the suggestion edits to the documentation and send a PR :)
