### ISSUE TITLE
problem with windows path

### ISSUE THREAD

**Issue by allanaari** [cuducos/alchemydumps#8]
There's some problem in backup.py
Can you make check  so that slashes doesn't get added to win path. 
Otherwise Backup works well with flask script and py 3.4, haven't tested restore jet. 
Thanks for this extension, makes life easier.

something like:
import sys

    @staticmethod
    def __slashes(string):
        """Adds, if needed, a slash to the beginning and ending of a string"""
        is_winows = sys.platform.startswith('win')
        if not is_winows:
            if string and len(string) > 1:
                if string[0:1] != '/':
                    string = '/{}'.format(string)
                if string[-1] != '/':
                    string = '{}/'.format(string)
        return string

**Comment by cuducos** [comment]
Hi @allanaari, thanks for the report!

I really don't have any Windows machine around here to test (and fix) this bug.

Have you implemented your solution and all tests end up green? If so, fell free to send a Pull Request :)

**Comment by allanaari** [comment]
confirm: Fix works with windows

**Comment by cuducos** [comment]
Many many thanks @allanaari and @racarvalho

Tomorrow first thing in the morning I merge this PR and upload a new version to pypi.

Once more: thank you both for fixing and testing!

**Comment by cuducos** [comment]
@allanaari, [version 0.0.9](https://pypi.python.org/pypi/Flask-AlchemyDumps/0.0.9) (just uploaded to PyPI) fixes this issue incorporating @rscarvalho's PR #9
